// ─────────────────────────────────────────────────────────────────────────────
// workOrderStore.js
//
// Lightweight module-level mutable array shared between Clients.jsx and
// WorkOrders.jsx.  No Redux / Context needed — both files import the same
// array reference, so Clients.push() is immediately visible when WorkOrders
// reads it on next render.
//
// WorkOrders uses a subscription pattern: call workOrderStore.subscribe(fn)
// to be notified whenever Clients pushes a new entry.
// ─────────────────────────────────────────────────────────────────────────────

export const seedWOs = [
  {
    id: "WO-2025-001",
    clientId: "SEED-001",
    client: "Arjun Mehta",
    clientEmail: "arjun@example.com",
    clientMobile: "9876543210",
    salesExec: "Rahul Singh",
    service: "Website Development",
    requirements: [
      { id: 1, title: "UI Design",   cost: "25000", description: "Homepage + 4 inner pages" },
      { id: 2, title: "Development", cost: "45000", description: "React frontend"           },
      { id: 3, title: "SEO Setup",   cost: "10000", description: "On-page optimisation"     },
    ],
    totalCost:     80000,
    discountMode:  "Flat",
    discountValue: "5000",
    discountAmt:   5000,
    netPayable:    75000,
    paymentStatus: "Advance",
    advanceAmount: "30000",
    terms: "50% advance, 50% on delivery. Revisions capped at 3.",
    generatedDate: "2025-07-01",
    signedStatus:  "Signed",
    approvalStatus:"Approved",
    approvalComment: "",
  },
  {
    id: "WO-2025-002",
    clientId: "SEED-002",
    client: "Priya Sharma",
    clientEmail: "priya@example.com",
    clientMobile: "9823456789",
    salesExec: "Aarti Verma",
    service: "ERP Integration",
    requirements: [
      { id: 4, title: "ERP Customisation", cost: "200000", description: "" },
      { id: 5, title: "Staff Training",     cost: "50000",  description: "3-day on-site sessions" },
    ],
    totalCost:     250000,
    discountMode:  "Percentage",
    discountValue: "4",
    discountAmt:   10000,
    netPayable:    240000,
    paymentStatus: "Unpaid",
    advanceAmount: "",
    terms: "30% advance, 40% mid, 30% on completion.",
    generatedDate: "2025-07-05",
    signedStatus:  "Unsigned",
    approvalStatus:"Pending",
    approvalComment: "",
  },
  {
    id: "WO-2025-003",
    clientId: "SEED-003",
    client: "Aditya Roy",
    clientEmail: "aditya@example.com",
    clientMobile: "9911223344",
    salesExec: "Rahul Singh",
    service: "Logo Design",
    requirements: [
      { id: 301, title: "Logo Concept Design", cost: "15000", description: "3 color variants" }
    ],
    totalCost:     15000,
    discountMode:  "None",
    discountValue: "",
    discountAmt:   0,
    netPayable:    15000,
    paymentStatus: "Paid",
    advanceAmount: "",
    terms: "100% advance payment.",
    generatedDate: "2025-07-06",
    signedStatus:  "Signed",
    approvalStatus:"Approved",
    approvalComment: "",
  },
  {
    id: "WO-2025-004",
    clientId: "SEED-004",
    client: "Nisha Patel",
    clientEmail: "nisha@example.com",
    clientMobile: "9898776655",
    salesExec: "Suresh Patel",
    service: "SEO",
    requirements: [
      { id: 401, title: "On-page Optimisation", cost: "20000", description: "" },
      { id: 402, title: "Backlink Audit", cost: "15000", description: "" }
    ],
    totalCost:     35000,
    discountMode:  "Percentage",
    discountValue: "10",
    discountAmt:   3500,
    netPayable:    31500,
    paymentStatus: "Unpaid",
    advanceAmount: "",
    terms: "Net 30 payment terms.",
    generatedDate: "2025-07-08",
    signedStatus:  "Unsigned",
    approvalStatus:"Pending",
    approvalComment: "",
  },
  {
    id: "WO-2025-005",
    clientId: "SEED-005",
    client: "Karan Johar",
    clientEmail: "karan@example.com",
    clientMobile: "9777665544",
    salesExec: "Aarti Verma",
    service: "Brand Identity",
    requirements: [
      { id: 501, title: "Brand Assets", cost: "70000", description: "" },
      { id: 502, title: "Brand Manual", cost: "50000", description: "" }
    ],
    totalCost:     120000,
    discountMode:  "Flat",
    discountValue: "20000",
    discountAmt:   20000,
    netPayable:    100000,
    paymentStatus: "Advance",
    advanceAmount: "40000",
    terms: "40% advance, 60% upon delivery.",
    generatedDate: "2025-07-10",
    signedStatus:  "Signed",
    approvalStatus:"Approved",
    approvalComment: "",
  },
  {
    id: "WO-2025-006",
    clientId: "SEED-006",
    client: "Shalini Sen",
    clientEmail: "shalini@example.com",
    clientMobile: "9666554433",
    salesExec: "Rahul Singh",
    service: "Google Ads",
    requirements: [
      { id: 601, title: "Google Search Ads", cost: "30000", description: "" },
      { id: 602, title: "Display Ads", cost: "15000", description: "" }
    ],
    totalCost:     45000,
    discountMode:  "None",
    discountValue: "",
    discountAmt:   0,
    netPayable:    45000,
    paymentStatus: "Paid",
    advanceAmount: "",
    terms: "Prepaid monthly budget.",
    generatedDate: "2025-07-12",
    signedStatus:  "Signed",
    approvalStatus:"Approved",
    approvalComment: "",
  },
  {
    id: "WO-2025-007",
    clientId: "SEED-007",
    client: "Vikram Malhotra",
    clientEmail: "vikram@example.com",
    clientMobile: "9555443322",
    salesExec: "Aarti Verma",
    service: "Website Development",
    requirements: [
      { id: 701, title: "Vite App Setup", cost: "40000", description: "" },
      { id: 702, title: "Component Library Integration", cost: "55000", description: "" }
    ],
    totalCost:     95000,
    discountMode:  "Percentage",
    discountValue: "5",
    discountAmt:   4750,
    netPayable:    90250,
    paymentStatus: "Advance",
    advanceAmount: "45000",
    terms: "50% advance, balance on completion.",
    generatedDate: "2025-07-14",
    signedStatus:  "Signed",
    approvalStatus:"Pending",
    approvalComment: "",
  },
  {
    id: "WO-2025-008",
    clientId: "SEED-008",
    client: "Rohan Bakshi",
    clientEmail: "rohan@example.com",
    clientMobile: "9444332211",
    salesExec: "Suresh Patel",
    service: "Landing Page",
    requirements: [
      { id: 801, title: "Landing Page UI Design", cost: "10000", description: "" },
      { id: 802, title: "Tailwind Implementation", cost: "15000", description: "" }
    ],
    totalCost:     25000,
    discountMode:  "Flat",
    discountValue: "2000",
    discountAmt:   2000,
    netPayable:    23000,
    paymentStatus: "Unpaid",
    advanceAmount: "",
    terms: "100% on delivery.",
    generatedDate: "2025-07-15",
    signedStatus:  "Unsigned",
    approvalStatus:"Rejected",
    approvalComment: "",
  },
  {
    id: "WO-2025-009",
    clientId: "SEED-009",
    client: "Deepika Rao",
    clientEmail: "deepika@example.com",
    clientMobile: "9333221100",
    salesExec: "Rahul Singh",
    service: "Social Media Marketing",
    requirements: [
      { id: 901, title: "Social Content Planning", cost: "30000", description: "" },
      { id: 902, title: "Graphic Designs (15 posts)", cost: "30000", description: "" }
    ],
    totalCost:     60000,
    discountMode:  "None",
    discountValue: "",
    discountAmt:   0,
    netPayable:    60000,
    paymentStatus: "Paid",
    advanceAmount: "",
    terms: "Monthly retainer.",
    generatedDate: "2025-07-18",
    signedStatus:  "Signed",
    approvalStatus:"Approved",
    approvalComment: "",
  },
  {
    id: "WO-2025-010",
    clientId: "SEED-010",
    client: "Sanjay Dutt",
    clientEmail: "sanjay@example.com",
    clientMobile: "9222110099",
    salesExec: "Suresh Patel",
    service: "ERP Integration",
    requirements: [
      { id: 1001, title: "ERP Middleware Setup", cost: "250000", description: "" },
      { id: 1002, title: "Custom API Adapters", cost: "200000", description: "" }
    ],
    totalCost:     450000,
    discountMode:  "Percentage",
    discountValue: "8",
    discountAmt:   36000,
    netPayable:    414000,
    paymentStatus: "Advance",
    advanceAmount: "150000",
    terms: "30% signoff, 40% milestone, 30% delivery.",
    generatedDate: "2025-07-20",
    signedStatus:  "Signed",
    approvalStatus:"Approved",
    approvalComment: "",
  },
  {
    id: "WO-2025-011",
    clientId: "SEED-011",
    client: "Meera Nair",
    clientEmail: "meera@example.com",
    clientMobile: "9111009988",
    salesExec: "Rahul Singh",
    service: "Content Writing",
    requirements: [
      { id: 1101, title: "Blog Writing (5 articles)", cost: "18000", description: "" }
    ],
    totalCost:     18000,
    discountMode:  "None",
    discountValue: "",
    discountAmt:   0,
    netPayable:    18000,
    paymentStatus: "Paid",
    advanceAmount: "",
    terms: "100% advance payment.",
    generatedDate: "2025-07-22",
    signedStatus:  "Signed",
    approvalStatus:"Approved",
    approvalComment: "",
  },
  {
    id: "WO-2025-012",
    clientId: "SEED-012",
    client: "Varun Dhawan",
    clientEmail: "varun@example.com",
    clientMobile: "9000998877",
    salesExec: "Aarti Verma",
    service: "Mobile App Development",
    requirements: [
      { id: 1201, title: "iOS App Development", cost: "180000", description: "" },
      { id: 1202, title: "Android App Development", cost: "170000", description: "" }
    ],
    totalCost:     350000,
    discountMode:  "Flat",
    discountValue: "50000",
    discountAmt:   50000,
    netPayable:    300000,
    paymentStatus: "Unpaid",
    advanceAmount: "",
    terms: "5 revisions, payment split over 4 sprints.",
    generatedDate: "2025-07-24",
    signedStatus:  "Unsigned",
    approvalStatus:"Pending",
    approvalComment: "",
  },
  {
    id: "WO-2025-013",
    clientId: "SEED-013",
    client: "Kriti Sanon",
    clientEmail: "kriti@example.com",
    clientMobile: "8999887766",
    salesExec: "Suresh Patel",
    service: "CRM Setup",
    requirements: [
      { id: 1301, title: "HubSpot Workspace Setup", cost: "50000", description: "" },
      { id: 1302, title: "Custom Sales Pipeline Config", cost: "35000", description: "" }
    ],
    totalCost:     85000,
    discountMode:  "Percentage",
    discountValue: "12",
    discountAmt:   10200,
    netPayable:    74800,
    paymentStatus: "Advance",
    advanceAmount: "30000",
    terms: "40% advance, balance post training.",
    generatedDate: "2025-07-26",
    signedStatus:  "Signed",
    approvalStatus:"Approved",
    approvalComment: "",
  },
  {
    id: "WO-2025-014",
    clientId: "SEED-014",
    client: "Siddharth Roy",
    clientEmail: "siddharth@example.com",
    clientMobile: "8888776655",
    salesExec: "Rahul Singh",
    service: "Meta Ads",
    requirements: [
      { id: 1401, title: "Facebook Page Ads Suite", cost: "30000", description: "" },
      { id: 1402, title: "Instagram Ads Management", cost: "25000", description: "" }
    ],
    totalCost:     55000,
    discountMode:  "None",
    discountValue: "",
    discountAmt:   0,
    netPayable:    55000,
    paymentStatus: "Paid",
    advanceAmount: "",
    terms: "Prepaid budget.",
    generatedDate: "2025-07-28",
    signedStatus:  "Signed",
    approvalStatus:"Approved",
    approvalComment: "",
  },
  {
    id: "WO-2025-015",
    clientId: "SEED-015",
    client: "Alia Bhatt",
    clientEmail: "alia@example.com",
    clientMobile: "8777665544",
    salesExec: "Aarti Verma",
    service: "Consulting",
    requirements: [
      { id: 1501, title: "Architecture consultation", cost: "100000", description: "" },
      { id: 1502, title: "Team training hours", cost: "50000", description: "" }
    ],
    totalCost:     150000,
    discountMode:  "Flat",
    discountValue: "15000",
    discountAmt:   15000,
    netPayable:    135000,
    paymentStatus: "Unpaid",
    advanceAmount: "",
    terms: "Due upon receipt of invoice.",
    generatedDate: "2025-07-30",
    signedStatus:  "Unsigned",
    approvalStatus:"Pending",
    approvalComment: "",
  },
  {
    id: "WO-2025-016",
    clientId: "SEED-016",
    client: "Ranbir Kapoor",
    clientEmail: "ranbir@example.com",
    clientMobile: "8666554433",
    salesExec: "Rahul Singh",
    service: "Video Editing",
    requirements: [
      { id: 1601, title: "Raw Footage Trimming", cost: "20000", description: "" },
      { id: 1602, title: "Color Grading & SFX", cost: "20000", description: "" }
    ],
    totalCost:     40000,
    discountMode:  "Percentage",
    discountValue: "15",
    discountAmt:   6000,
    netPayable:    34000,
    paymentStatus: "Paid",
    advanceAmount: "",
    terms: "Per-video pricing structure.",
    generatedDate: "2025-08-01",
    signedStatus:  "Signed",
    approvalStatus:"Approved",
    approvalComment: "",
  },
  {
    id: "WO-2025-017",
    clientId: "SEED-017",
    client: "Kiara Advani",
    clientEmail: "kiara@example.com",
    clientMobile: "8555443322",
    salesExec: "Aarti Verma",
    service: "Brand Identity",
    requirements: [
      { id: 1701, title: "Brand Assets Package", cost: "90000", description: "" }
    ],
    totalCost:     90000,
    discountMode:  "None",
    discountValue: "",
    discountAmt:   0,
    netPayable:    90000,
    paymentStatus: "Advance",
    advanceAmount: "45000",
    terms: "50% advance retainer.",
    generatedDate: "2025-08-03",
    signedStatus:  "Signed",
    approvalStatus:"Approved",
    approvalComment: "",
  },
];

const listeners = new Set();

export const workOrderStore = {
  _data: [...seedWOs],

  /** Called by Clients.jsx when "Send to Client" fires on an Interested row */
  push(wo) {
    this._data = [...this._data, wo];
    listeners.forEach((fn) => fn(this._data));
  },

  /** Returns the current snapshot */
  getAll() {
    return this._data;
  },

  /** WorkOrders.jsx calls this in a useEffect to stay in sync */
  subscribe(fn) {
    listeners.add(fn);
    return () => listeners.delete(fn); // returns unsubscribe
  },
};